development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: redis://localhost:6379/1
  url: redis://redistogo:57ae0a1db7057aaa7faa3b98a59e2c02@grouper.redistogo.com:11719/
  # channel_prefix: slack_clone_production
